DudiGames/Controllers/CapitalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DudiGames.Service;
using DudiGames.Models;

namespace DudiGames.Controllers
{
    public class CapitalController : Controller

    {
        private readonly CapitalService _capitalService;
        private readonly FinanceiroService _financeiroService;

        public CapitalController(CapitalService capitalService, FinanceiroService financeiroService)
        {
            _capitalService = capitalService;
            _financeiroService = financeiroService;
        }

        public IActionResult Index()
        {
            var list = _capitalService.FindAll();
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Capital capital)
         {
            if (!ModelState.IsValid)
            {
                return View(capital);
            }


           _capitalService.AdicionarCapital(capital);
   
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? Id)
        {
            var obj = _capitalService.FindById(Id.Value);
            if (Id == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Capital capital)
        {
            if (!ModelState.IsValid)
            {
                return View(capital);
            }

            _capitalService.EditarCapital(capital);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? Id)
        {
            var obj = _capitalService.FindById(Id.Value);
            if (Id == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        public IActionResult Delete(int? Id)
        {
            var obj = _capitalService.FindById(Id.Value);
            if (Id == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Capital capital)
        {
            _capitalService.RemoverCapital(capital);
            return RedirectToAction(nameof(Index));
        }
    }
}

DudiGames/Controllers/ClientesController.cs
using DudiGames.Models;
using DudiGames.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DudiGames.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClienteService _clienteService;

        public ClientesController(ClienteService clienteService)
        {
            _clienteService = clienteService;
        }

        public IActionResult Index()
        {
            var list = _clienteService.FindAll();
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cliente cliente)
        {
            if (!ModelState.IsValid)
            {
                return View(cliente);
            }

            _clienteService.AdicionarCliente(cliente);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? Id)
        {
            var obj = _clienteService.FindById(Id.Value);
            if(Id == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult  Edit (Cliente cliente)
        {
            if (!ModelState.IsValid)
            {
                return View(cliente);
            }

            _clienteService.EditarCliente(cliente);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? Id)
        {
            var obj = _clienteService.FindById(Id.Value);
            if(Id == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        public IActionResult Delete (int? Id)
        {
            var obj = _clienteService.FindById(Id.Value);
            if (Id == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete (Cliente cliente)
        {
            _clienteService.RemoverCliente(cliente);
            return RedirectToAction(nameof(Index));
        }
    }
}

DudiGames/Controllers/EstoquesController.cs
using DudiGames.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DudiGames.Controllers
{
    public class EstoquesController : Controller
    {
        private readonly EstoqueService _estoqueService;
        private readonly CompraService _compraService;

        public EstoquesController(EstoqueService estoqueService, CompraService compraService)
        {
            _estoqueService = estoqueService;
            _compraService = compraService;
        }

        public IActionResult Index()
        {
            var lista = _estoqueService.FindAll();
            ViewBag.ValorTotal = _estoqueService.ValorTotalEstoque();
            ViewBag.TotalProdutos = _estoqueService.TotalProdutosEstoque();
            
            return View(lista);
        }
    }
}

DudiGames/Controllers/PedidosController.cs
using DudiGames.Models;
using DudiGames.Models.ViewModel;
using DudiGames.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DudiGames.Controllers
{
    public class PedidosController : Controller
    {
        private readonly PedidoService _pedidoService;
        private readonly EstoqueService _estoqueService;
        private readonly ProdutoService _produtoService;
        private readonly ClienteService _clienteService;
        private readonly FinanceiroService _financeiroService;

        public PedidosController(PedidoService pedidoService, EstoqueService estoqueService, ProdutoService produtoService, ClienteService clienteService, FinanceiroService financeiroService)
        {
            _pedidoService = pedidoService;
            _estoqueService = estoqueService;
            _produtoService = produtoService;
            _clienteService = clienteService;
            _financeiroService = financeiroService;
        }

        public IActionResult Index()
        {
            var list = _pedidoService.FindAll();
            return View(list);
        }

        public IActionResult Create()
        {
            ViewBag.ProdutoId = _produtoService.FindAll();
            ViewBag.ClienteId = _clienteService.FindAll();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PedidoViewModel pedidoViewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProdutoId = _produtoService.FindAll();
                ViewBag.ClienteId = _clienteService.FindAll();
                return View(pedidoViewModel);
            }

            
            _pedidoService.AdicionarPedido(pedidoViewModel);
            var estoque = _pedidoService.BuscarEstoque(pedidoViewModel.ProdutoId);
            _pedidoService.RemoverEstoque(pedidoViewModel);
           
            _financeiroService.SalvarFinanceiro(pedidoViewModel);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var obj = _pedidoService.FindById(id.Value);
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var obj = _pedidoService.FindById(id.Value);
            ViewBag.ProdutoId = _produtoService.FindAll();
            ViewBag.ClienteId = _clienteService.FindAll();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PedidoViewModel pedidoViewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProdutoId = _produtoService.FindAll();
                ViewBag.ClienteId = _clienteService.FindAll();
                return View(pedidoViewModel);
            }
            _pedidoService.EditarPedido(pedidoViewModel);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var obj = _pedidoService.FindById(id.Value);
            
            
            return View(obj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var compra = _pedidoService.FindById(id);
            _pedidoService.RemoverPedido(id);
            //_estoqueService.RemoverEstoque(compra);
            return RedirectToAction(nameof(Index));

        }
    }
}

DudiGames/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dudi Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dudi Games</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoques" asp-action="Index">Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Venda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Financeiros" asp-action="Index">Financeiro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Capital" asp-action="Index">Capital</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Dudi Games - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>